### ISSUE TITLE
[BUG] it highlights a math formula when it's not a block reference

### ISSUE THREAD

**Issue by hyperphysin** [isdmg/obsidian-remove-unused-block-ids#2]
There's a unused block reference in the second line.
![Screenshot 2024-09-25 at 9 28 43 AM](https://github.com/user-attachments/assets/1b5c06a4-a6f8-4617-b04d-b276c0424dfc)

But it highlights the first one.
![Screenshot 2024-09-25 at 9 29 33 AM](https://github.com/user-attachments/assets/f62b760a-b58a-4ef6-a5f9-0c7e720581f9)

**Comment by isdmg** [comment]
Thank you for bringing this to my attention. It should be fixed in [1.0.4](https://github.com/isdmg/obsidian-remove-unused-block-ids/releases/tag/1.0.4). Could you confirm?

**Comment by hyperphysin** [comment]
> Thank you for bringing this to my attention. It should be fixed in [1.0.4](https://github.com/isdmg/obsidian-remove-unused-block-ids/releases/tag/1.0.4). Could you confirm?

It works corretly now.
