### ISSUE TITLE
[BUG] it detects ^ in code blocks.

### ISSUE THREAD

**Issue by hyperphysin** [isdmg/obsidian-remove-unused-block-ids#3]
```
x=a^2
```
It thinks it's a block reference.

**Comment by isdmg** [comment]
I fixed it in [1.0.5](https://github.com/isdmg/obsidian-remove-unused-block-ids/releases/tag/1.0.5). Please check if it works now. However, in this change, it would not detect `a^2` in your previous issue (#2) as a block id anymore since it is an invalid block id anyways.

**Comment by hyperphysin** [comment]
> I fixed it in [1.0.5](https://github.com/isdmg/obsidian-remove-unused-block-ids/releases/tag/1.0.5). Please check if it works now. However, in this change, it would not detect `a^2` in your previous issue (#2) as a block id anymore since it is an invalid block id anyways.

I just checked it was fixed. Thank you.
