### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by DutchPete** [isdmg/obsidian-remove-unused-block-ids#4]
Many thanks for a piece of garbage!! I stupidly applied it to my vault and ALL my embeds are gone because that crap deletes everything, NOT just unused block ID. I shall report this as malware.

**Comment by isdmg** [comment]
It would be for the best if you could provide steps to reproduce your issue. I have tried this plugin on multiple vaults and I have yet to run to your issue.

See this gif for an example:

https://github.com/user-attachments/assets/4e886348-29a9-4efb-a5ba-9fe630c81aa7

Lastly, please back up your files next time, especially when running a plugin that modifies the content of your files.

**Comment by DutchPete** [comment]
There are no special steps. I installed your plug-in, then ran it.
One of the files that was open only had internal links, i.e. blocks of text from that file were embedded at the top of that file. So, each block ID occurred at least 2x in that file, but all the IDs at the original blocks were deleted, leaving orphaned IDs were the embeds are supposed to be.

In another file some internal embeds were treated the same, others were not; in that file some embeds from other files were also treated that way, others were left intact.

So, your testing was probably done on a few very simple files instead of in a real life situation.

**Comment by isdmg** [comment]
Are the reference to your block links inside a canvas file?

**Comment by isdmg** [comment]
I could not reproduce your issues. However, if you are able to reproduce it on your side again, please share your vault so that I can see what went wrong exactly. Thank you.

**Comment by DutchPete** [comment]
Of course you could not reproduce it, I would not expect anything else.
And do you really think I would share my vault with outsiders? You're dreaming.
Thank you too, for crap.
